---
title: "IMSCO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Load packages
```{r}
library(tidyverse)
library(reshape2)
library(lubridate)
library(rebus)
library(Matrix)
```

###Loading data
```{r}
d <- read_csv("IMSCO 3 YEAR HISTORY.csv.xls")
```

###Exploratory Data Analysis
#####Head of Data
```{r}
head(d)
```

#####Summary
```{r}
summary(d)
```

#####Converting column names to R naming conventions
```{r}
colnames(d) <- colnames(d) %>% 
  tolower() %>% 
  str_replace_all(" ", "_")

colnames(d)
```

#####Setting correct column classes
```{r}
d$product_number <- as.factor(d$product_number)
d$order_date <- mdy(d$order_date)

summary(d)
```

#####Aggregating data by month
```{r}
d_monthly <- select(d, c(order_date, product_number, quantity_billed)) %>% 
  group_by(month = floor_date(order_date, "month"), product_number = product_number) %>% 
  summarize(quantity_billed = sum(quantity_billed))

head(d_monthly)
```

#####Standardized
```{r}
d_m_standard <- d_monthly %>% 
  mutate(quantity_billed = scale(quantity_billed))

head(d_m_standard)
```


#####Creating wide data set on dates
```{r}
d_dates <- d_monthly %>% 
  spread(product_number, quantity_billed, fill = 0)
```

```{r}
head(d_dates)
```

#####Standardized
```{r}
d_d_standard <- d_m_standard %>% 
  spread(product_number, quantity_billed, fill = 0)
```

```{r}
head(d_d_standard)
```


#####Creating wide dataset on products
```{r}
d_products <- d_monthly %>% 
  spread(month, quantity_billed, fill = 0)
```

```{r}
head(d_products)
```

```{r}
d_p_standard <- d_m_standard %>% 
  spread(month, quantity_billed, fill = 0)
```

```{r}
head(d_p_standard)
```

```{r}
#This is testing the branch feature
#More testing 
```

